from __future__ import annotations

import json
import secrets
import sqlite3
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from typing import List, Optional

import anyio


# ── Code alphabet (avoids visually ambiguous chars: 0/O/I/1) ──────────────────
_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
_CODE_LEN = 8


def _gen_raw() -> str:
    return "".join(secrets.choice(_ALPHABET) for _ in range(_CODE_LEN))


# ── Record ─────────────────────────────────────────────────────────────────────

@dataclass(frozen=True)
class AccessCodeRecord:
    id: int
    code: str
    tenant_slug: str
    role: str
    title: Optional[str]
    created_by_user_id: int
    created_at: str
    expires_at: str
    max_uses: int
    use_count: int
    last_used_at: Optional[str]
    status: str             # active | used | expired | revoked
    is_setup_code: bool     # True = district-admin bootstrap code
    invite_email: Optional[str]


# ── Service ────────────────────────────────────────────────────────────────────

class AccessCodeService:
    """
    Platform-level access-code store (lives in platform.db).

    Security contract:
    - Codes are cryptographically random (secrets module).
    - is_setup_code=True rows are only generated by super_admin and only
      consumed by the create-district-admin endpoint.
    - Normal codes are only generated by district_admin (and only for
      CODEGEN_ALLOWED_ROLES) and only consumed within their assigned tenant.
    - consume_code is atomic — the status/use_count update and the caller's
      user-creation must both succeed or neither should be committed.
      Callers should consume the code AFTER successfully creating the user;
      idempotency is protected by the UNIQUE code constraint.
    """

    def __init__(self, db_path: str) -> None:
        self._db_path = db_path
        self._init_db()

    # ── DB plumbing ────────────────────────────────────────────────────────────

    def _connect(self) -> sqlite3.Connection:
        return sqlite3.connect(self._db_path, timeout=30, isolation_level=None)

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.execute("PRAGMA journal_mode=WAL;")
            conn.execute(
                """
                CREATE TABLE IF NOT EXISTS access_codes (
                    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                    code                TEXT    NOT NULL UNIQUE,
                    tenant_slug         TEXT    NOT NULL,
                    role                TEXT    NOT NULL,
                    title               TEXT    NULL,
                    created_by_user_id  INTEGER NOT NULL DEFAULT 0,
                    created_at          TEXT    NOT NULL,
                    expires_at          TEXT    NOT NULL,
                    max_uses            INTEGER NOT NULL DEFAULT 1,
                    use_count           INTEGER NOT NULL DEFAULT 0,
                    last_used_at        TEXT    NULL,
                    status              TEXT    NOT NULL DEFAULT 'active',
                    is_setup_code       INTEGER NOT NULL DEFAULT 0,
                    invite_email        TEXT    NULL
                );
                """
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_ac_code ON access_codes(code);"
            )
            conn.execute(
                "CREATE INDEX IF NOT EXISTS idx_ac_tenant ON access_codes(tenant_slug, is_setup_code);"
            )

    # ── Internal helpers ───────────────────────────────────────────────────────

    @staticmethod
    def _effective_status(row: tuple, now_iso: str) -> str:
        status = str(row[11])
        if status == "active":
            if str(row[7]) <= now_iso:
                return "expired"
            if int(row[9]) >= int(row[8]):
                return "used"
        return status

    @staticmethod
    def _row_to_record(row: tuple, now_iso: Optional[str] = None) -> AccessCodeRecord:
        status = AccessCodeService._effective_status(row, now_iso or datetime.now(timezone.utc).isoformat())
        return AccessCodeRecord(
            id=int(row[0]),
            code=str(row[1]),
            tenant_slug=str(row[2]),
            role=str(row[3]),
            title=str(row[4]) if row[4] else None,
            created_by_user_id=int(row[5]),
            created_at=str(row[6]),
            expires_at=str(row[7]),
            max_uses=int(row[8]),
            use_count=int(row[9]),
            last_used_at=str(row[10]) if row[10] else None,
            status=status,
            is_setup_code=bool(int(row[12])),
            invite_email=str(row[13]) if row[13] else None,
        )

    # ── Generate ───────────────────────────────────────────────────────────────

    def _generate_sync(
        self,
        tenant_slug: str,
        role: str,
        title: Optional[str],
        created_by_user_id: int,
        expires_at: datetime,
        max_uses: int,
        is_setup_code: bool,
    ) -> AccessCodeRecord:
        now_iso = datetime.now(timezone.utc).isoformat()
        expires_iso = expires_at.isoformat()
        for _ in range(20):
            code = _gen_raw()
            try:
                with self._connect() as conn:
                    conn.execute(
                        """
                        INSERT INTO access_codes
                            (code, tenant_slug, role, title, created_by_user_id,
                             created_at, expires_at, max_uses, is_setup_code)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
                        """,
                        (
                            code, tenant_slug, role, title, created_by_user_id,
                            now_iso, expires_iso, max_uses,
                            1 if is_setup_code else 0,
                        ),
                    )
                    row_id = conn.execute("SELECT last_insert_rowid();").fetchone()[0]
                return AccessCodeRecord(
                    id=int(row_id),
                    code=code,
                    tenant_slug=tenant_slug,
                    role=role,
                    title=title,
                    created_by_user_id=created_by_user_id,
                    created_at=now_iso,
                    expires_at=expires_iso,
                    max_uses=max_uses,
                    use_count=0,
                    last_used_at=None,
                    status="active",
                    is_setup_code=is_setup_code,
                    invite_email=None,
                )
            except sqlite3.IntegrityError:
                continue  # code collision — retry
        raise RuntimeError("Failed to generate a unique access code after 20 attempts")

    async def generate_code(
        self,
        *,
        tenant_slug: str,
        role: str,
        title: Optional[str] = None,
        created_by_user_id: int = 0,
        expires_hours: int = 48,
        max_uses: int = 1,
        is_setup_code: bool = False,
    ) -> AccessCodeRecord:
        expires_at = datetime.now(timezone.utc) + timedelta(hours=expires_hours)
        return await anyio.to_thread.run_sync(
            lambda: self._generate_sync(
                tenant_slug, role, title, created_by_user_id,
                expires_at, max_uses, is_setup_code,
            )
        )

    # ── Validate (read-only, does not consume) ─────────────────────────────────

    def _validate_sync(
        self, code: str, tenant_slug: str, is_setup_code: bool
    ) -> Optional[AccessCodeRecord]:
        now_iso = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            row = conn.execute(
                """
                SELECT id, code, tenant_slug, role, title, created_by_user_id, created_at,
                       expires_at, max_uses, use_count, last_used_at, status, is_setup_code,
                       invite_email
                FROM access_codes
                WHERE code = ?
                  AND tenant_slug = ?
                  AND is_setup_code = ?
                  AND status = 'active'
                  AND expires_at > ?
                  AND use_count < max_uses;
                """,
                (
                    code.upper().strip(),
                    tenant_slug,
                    1 if is_setup_code else 0,
                    now_iso,
                ),
            ).fetchone()
        if not row:
            return None
        return self._row_to_record(row, now_iso)

    async def validate_code(
        self, code: str, tenant_slug: str
    ) -> Optional[AccessCodeRecord]:
        return await anyio.to_thread.run_sync(
            lambda: self._validate_sync(code, tenant_slug, is_setup_code=False)
        )

    async def validate_setup_code(
        self, code: str, tenant_slug: str
    ) -> Optional[AccessCodeRecord]:
        return await anyio.to_thread.run_sync(
            lambda: self._validate_sync(code, tenant_slug, is_setup_code=True)
        )

    # ── Consume (marks used / decrements remaining uses) ───────────────────────

    def _consume_sync(self, code_id: int) -> bool:
        now_iso = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            result = conn.execute(
                """
                UPDATE access_codes
                SET use_count    = use_count + 1,
                    last_used_at = ?,
                    status       = CASE
                                     WHEN use_count + 1 >= max_uses THEN 'used'
                                     ELSE 'active'
                                   END
                WHERE id = ? AND status = 'active' AND expires_at > ? AND use_count < max_uses;
                """,
                (now_iso, code_id, now_iso),
            )
            return result.rowcount > 0

    async def consume_code(self, code_id: int) -> bool:
        """Returns True if code was successfully consumed. Thread-safe."""
        return await anyio.to_thread.run_sync(lambda: self._consume_sync(code_id))

    # ── Revoke ─────────────────────────────────────────────────────────────────

    def _revoke_sync(self, code_id: int, tenant_slug: str) -> bool:
        with self._connect() as conn:
            result = conn.execute(
                "UPDATE access_codes SET status = 'revoked' WHERE id = ? AND tenant_slug = ?;",
                (code_id, tenant_slug),
            )
            return result.rowcount > 0

    async def revoke_code(self, code_id: int, tenant_slug: str) -> bool:
        return await anyio.to_thread.run_sync(
            lambda: self._revoke_sync(code_id, tenant_slug)
        )

    # ── Set invite email ───────────────────────────────────────────────────────

    def _set_invite_email_sync(self, code_id: int, tenant_slug: str, email: str) -> bool:
        with self._connect() as conn:
            result = conn.execute(
                "UPDATE access_codes SET invite_email = ? WHERE id = ? AND tenant_slug = ?;",
                (email, code_id, tenant_slug),
            )
            return result.rowcount > 0

    async def set_invite_email(self, code_id: int, tenant_slug: str, email: str) -> bool:
        return await anyio.to_thread.run_sync(
            lambda: self._set_invite_email_sync(code_id, tenant_slug, email)
        )

    # ── List ───────────────────────────────────────────────────────────────────

    def _list_sync(
        self, tenant_slug: str, is_setup_code: bool, limit: int
    ) -> List[AccessCodeRecord]:
        now_iso = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT id, code, tenant_slug, role, title, created_by_user_id, created_at,
                       expires_at, max_uses, use_count, last_used_at, status, is_setup_code,
                       invite_email
                FROM access_codes
                WHERE tenant_slug = ? AND is_setup_code = ?
                ORDER BY id DESC LIMIT ?;
                """,
                (tenant_slug, 1 if is_setup_code else 0, limit),
            ).fetchall()
        return [self._row_to_record(r, now_iso) for r in rows]

    async def list_codes(
        self, tenant_slug: str, *, limit: int = 200
    ) -> List[AccessCodeRecord]:
        return await anyio.to_thread.run_sync(
            lambda: self._list_sync(tenant_slug, False, limit)
        )

    def _list_all_setup_sync(self, limit: int) -> List[AccessCodeRecord]:
        now_iso = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT id, code, tenant_slug, role, title, created_by_user_id, created_at,
                       expires_at, max_uses, use_count, last_used_at, status, is_setup_code,
                       invite_email
                FROM access_codes
                WHERE is_setup_code = 1
                ORDER BY id DESC LIMIT ?;
                """,
                (limit,),
            ).fetchall()
        return [self._row_to_record(r, now_iso) for r in rows]

    async def list_setup_codes(self, *, limit: int = 200) -> List[AccessCodeRecord]:
        return await anyio.to_thread.run_sync(
            lambda: self._list_all_setup_sync(limit)
        )

    # ── Analytics helpers ──────────────────────────────────────────────────────

    def _stats_sync(self, tenant_slug: str) -> dict:
        now_iso = datetime.now(timezone.utc).isoformat()
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT status,
                       CASE WHEN expires_at <= ? AND status = 'active' THEN 'expired' ELSE status END
                           AS eff_status,
                       COUNT(*)
                FROM access_codes
                WHERE tenant_slug = ? AND is_setup_code = 0
                GROUP BY eff_status;
                """,
                (now_iso, tenant_slug),
            ).fetchall()
        return {str(r[1]): int(r[2]) for r in rows}

    async def stats(self, tenant_slug: str) -> dict:
        return await anyio.to_thread.run_sync(lambda: self._stats_sync(tenant_slug))

    # ── QR payload helper ──────────────────────────────────────────────────────

    @staticmethod
    def qr_payload(code: str, tenant_slug: str, is_setup: bool = False) -> str:
        return json.dumps(
            {
                "type": "bluebird_setup" if is_setup else "bluebird_invite",
                "code": code,
                "tenant_slug": tenant_slug,
            },
            separators=(",", ":"),
        )

    @staticmethod
    def invite_url(
        code: str, tenant_slug: str, base_domain: str, is_setup: bool = False
    ) -> str:
        path = "setup" if is_setup else "onboarding"
        return f"https://{base_domain}/{path}?code={code}&tenant={tenant_slug}"
